### ISSUE TITLE
Class hierarchy isn't considered

### ISSUE THREAD

**Issue by twallmey** [cyberborean/rdfbeans#34]
Hi,

I've created several (Java) beans with a simple hierarchy (e.g. A-->B). When I'm instantiating objects (a, b) of these classes and have a look at the resulting RDF statements, everything looks fine but I'm missing the type hierarchy in RDF. I do see:

A type a
B type b

but I'm missing:

B subclassOf A

I would assume that the subclass statements are generated as well because they could easily by extracted from the defined class hierarchy in Java. What do I have to do in order to get these statements generated as well?

Additional comment:

Just looked into the code and found this line within org.cyberborean.rdfbeans.impl.Marshaller that should be extended to consider the type hierarchy as well. Currently it just focusses on the concrete JavaBean type.

conn.add(subject, RDF.TYPE, type, contexts);

**Comment by cyberborean** [comment]
good idea!
